---
- name: Install git
  ansible.builtin.yum:
    name: git
    state: latest
- block:
    - name: Get lighthouse
      ansible.builtin.shell: git clone https://github.com/VKCOM/lighthouse
  rescue:
    - name: Already get
      ansible.builtin.shell: echo OK
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: latest
- name: Nginx start
  ansible.builtin.shell: systemctl start nginx | systemctl enable nginx
- name: Copy lighthouse to Nginx
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/* | cp -r -f lighthouse/* /usr/share/nginx/html
- name: Restart Nginx
  ansible.builtin.shell: service nginx restart